#robot_radius: 0.0

#obstacle_range: 2.5
#raytrace_range: 3.0
footprint: [[0.27, 0.22], [0.27, -0.22], [-0.27, -0.22], [-0.27, 0.22]]
footprint_inflation: 0.005

static_layer:
  enabled: true
  unknown_cost_value: -1
  lethal_cost_threshold: 100
  map_topic: map
  first_map_only: false
  subscribe_to_updates: true
  track_unknown_space: true
  use_maximum: false
  trinary_costmap: true
  
obstacle_layer:
  enabled: true
  observation_sources: scan
  scan:
    topic: scan
    sensor_frame: laser_link
    data_type: LaserScan
    clearing: true
    marking: true
  obstacle_range: 2.0
  raytrace_range: 3.0
  track_unknown_space: true
  combination_method: 1
  
inflation_layer:
  enabled: true
  inflation_radius: 1.75 
  cost_scaling_factor: 2.58


#inflation_radius: 1.75 #0.35
#cost_scaling_factor: 2.25

#max_obstacle_height: 0.8  scan_filtered

#observation_sources: scan
#scan: {data_type: LaserScan, topic: /scan, marking: true, clearing: true}

