DWAPlannerROS:

 acc_lim_x: 1.0
 acc_lim_y: 0.0
 acc_lim_th: 2.0
 max_vel_trans: 0.5
 min_vel_trans: 0.1
 max_vel_x: 0.5
 min_vel_x: 0.0
 max_vel_y: 0.0
 min_vel_y: 0.0
 max_rot_vel: 0.5
 min_rot_vel: -0.5
 
 xy_goal_tolerance: 0.05
 yaw_goal_tolerance: 0.05
 latch_xy_goal_tolerance: false

 sim_time: 3.0
 sim_granularity: 0.025
 vx_samples: 20
 vy_samples: 0
 vth_samples: 40
 
 path_distance_bias: 32.0
 goal_distance_bias: 24.0
 pdist_scale: 3.0
 gdist_scale: 1.5
 occdist_scale: 0.01
 forward_point_distance: 0.325
 stop_time_buffer: 0.05
 scaling_speed: 0.25
 max_scaling_factor: 0.2
 publish_cost_grid: false
 
 oscillation_reset_dist: 0.05
 
 prune_plan: true
 publish_traj_pc: true
 publish_cost_grid_pc: false
 
 global_frame_id: odom
 dwa: true
 
