global_costmap:
   global_frame: map
   robot_base_frame: base_link #base_footprint
   update_frequency: 1.0
   publish_frequency: 1.0
   static_map: true
   rolling_window: false
   resolution: 0.02
   unknown_cost_value: 255
   #transform_tolerance: 1.0 VoxelLayer
   map_type: costmap 
   
   transform_tolerance: 0.5
   #plugins:
   # - {name: static_layer,            type: "costmap_2d::StaticLayer"}
   # - {name: obstacle_layer,          type: "costmap_2d::ObstacleLayer"}
   # - {name: inflation_layer,         type: "costmap_2d::InflationLayer"}
    

    
