
#---standard pioneer footprint---
#---(in meters)---
#robot_radius: 0.17
footprint: [[0.25, 0.2], [0.25, -0.2], [-0.25, -0.2], [-0.25, 0.2]]
footprint_padding: 0.00

transform_tolerance: 5.0
#map_type: costmap
#z_voxels: 20
#always_send_full_costmap: true

obstacle_layer:
 enabled: true
 obstacle_range: 4.5
 raytrace_range: 5.0
 inflation_radius: 0.3
 track_unknown_space: false
 combination_method: 1
 #scan_filtered
 observation_sources: bump scan_wj_1 scan_wj_2  #scan_rpl # #bump  # 
 #scan_rpl: 
 #  data_type: LaserScan
 #  topic: /scan_filtered
 #  marking: true
 #  clearing: true
 scan_wj_1: {data_type: LaserScan,topic: /scan_wj_1,marking: true,clearing: true}
 scan_wj_2: {data_type: LaserScan,topic: /scan_wj_2,marking: true,clearing: true}
 bump: {data_type: PointCloud2,topic: /scan_matched_points2,marking: true, clearing: true}


inflation_layer_global:
  enabled:              true
  cost_scaling_factor:  12.0  # exponential rate at which the obstacle cost drops off (default: 10)
  inflation_radius:     0.5  # max. distance from an obstacle at which costs are incurred for planning paths.

inflation_layer_local:
  enabled:              true
  cost_scaling_factor:  12.0
  inflation_radius:     0.5
  
static_layer:
  enabled:              true
  map_topic:            "/map"
  

