#robot_radius: 0.25

obstacle_range: 2.5
raytrace_range: 3.0
footprint: [[0.27, 0.22], [0.27, -0.22], [-0.27, -0.22], [-0.27, 0.22]]
footprint_inflation: 0.005

inflation_radius: 0.05 #0.35
cost_scaling_factor: 8.25

#max_obstacle_height: 0.8

observation_sources: scan
scan: {data_type: LaserScan, topic: /scan_filtered, marking: true, clearing: true}

