DWAPlannerROS:
  acc_lim_x: 1.5
  acc_lim_y: 0.0
  acc_lim_theta: 4.5
  max_vel_theta: 1.5 #0.5
  min_vel_theta: 0.8
  max_vel_x: 0.5
  min_vel_x: 0.0
  max_vel_y: 0.0
  min_vel_y: 0.0
  max_vel_trans: 0.5
  min_vel_trans: 0.1
  trans_stopped_vel: 0.1
  theta_stopped_vel: 0.4

  xy_goal_tolerance: 0.06
  yaw_goal_tolerance: 0.06
  latch_xy_goal_tolerance: false

  sim_time: 3.0 # 1.5
  sim_granularity: 0.025
  vx_samples: 20
  vy_samples: 1
  vth_samples: 40

  path_distance_bias: 90.0
  goal_distance_bias: 24.0
  occdist_scale: 0.05
  forward_point_distance: 0.325
  stop_time_buffer: 1.2
  scaling_speed: 0.25
  max_scaling_factor: 0.2
  publish_cost_grid: false
  meter_scoring: true

  oscillation_reset_dist: 0.05

  prune_plan: false
  publish_traj_pc: true
  publish_cost_grid_pc: true

  global_frame_id: odom_combined
