global_costmap:
   global_frame: map
   robot_base_frame: base_link #base_footprint
   update_frequency: 5.0
   publish_frequency: 0
   #static_map: true
   
   rolling_window: false
   resolution: 0.05
   transform_tolerance: 5.0
   #map_type: costmap
   plugins:
    - {name: static_layer,            type: "costmap_2d::StaticLayer"}
    - {name: obstacle_layer,          type: "costmap_2d::ObstacleLayer"}  #VoxelLayer
    #- {name: costmap_prohibition_layer,         type: "costmap_prohibition_layer_namespace::CostmapProhibitionLayer"}
    - {name: inflation_layer_global,         type: "costmap_2d::InflationLayer"}
