local_costmap:
   # coordinate frame and tf parameters
   global_frame: odom_combined
   robot_base_frame: base_link # base_footprint
   transform_tolerance: 5.0 #5

   # rate parameters
   update_frequency: 5.0
   publish_frequency: 2.0

   # map params
   static_map: false
   rolling_window: true
   resolution: 0.01

   width: 10.0
   height: 10.0

   map_type: costmap

   plugins:
      - { name: obstacle_layer, type: "costmap_2d::ObstacleLayer" }
      - { name: inflation_layer_local, type: "costmap_2d::InflationLayer" }
      #- {name: costmap_prohibition_layer,         type: "costmap_prohibition_layer_namespace::CostmapProhibitionLayer"}
